swagger: "2.0"
info:
    title: Order Mangament Service
    description: Microservice for manager Order
    version: ""
host: localhost:30001
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/v4/msorderms/order:
        post:
            tags:
                - msorderms
            summary: createOrder msorderms
            operationId: msorderms#createOrder
            parameters:
                - name: CreateOrderRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/MsordermsCreateOrderRequestBody'
                    required:
                        - idOrdine
                        - store
                        - tipologiaOrdine
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/MsordermsCreateOrderResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
            schemes:
                - http
    /api/v4/msorderms/order/{idOrdine}:
        get:
            tags:
                - msorderms
            summary: getStatusOrderById msorderms
            operationId: msorderms#getStatusOrderById
            parameters:
                - name: idOrdine
                  in: path
                  description: IdOrdine
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/MsordermsGetStatusOrderByIDResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/MsordermsGetStatusOrderByIDNoMatchResponseBody'
            schemes:
                - http
    /api/v4/msorderms/sayHello:
        get:
            tags:
                - msorderms
            summary: sayHello msorderms
            operationId: msorderms#sayHello
            parameters:
                - name: name
                  in: query
                  description: Name
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
    /swagger/swagger.json:
        get:
            tags:
                - swagger
            summary: Download gen/http/openapi.json
            description: JSON document containing the API swagger definition
            operationId: swagger#/swagger/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    MsordermsCreateOrderRequestBody:
        title: MsordermsCreateOrderRequestBody
        type: object
        properties:
            cognomeCliente:
                type: string
                description: Cognome Cliente
                example: Ratione suscipit et officiis quis minus quae.
            dataOrdine:
                type: string
                description: Data Ordine
                example: Vel facilis neque.
            idOrdine:
                type: string
                description: Id Ordine
                example: Molestiae natus ex eaque animi.
            nomeCliente:
                type: string
                description: Nome Cliente
                example: Illum magni cumque.
            righeOrdine:
                type: array
                items:
                    $ref: '#/definitions/RigaOrdineRequestBody'
                description: Righe Ordine
                example:
                    - barcode: Et consectetur.
                      colore: Voluptatem non sunt ea.
                      modello: Alias tenetur.
                      prezzo: 0.78429174
                      quantita: 7708216444412231043
                      taglia: Nobis minima sit a qui.
                    - barcode: Et consectetur.
                      colore: Voluptatem non sunt ea.
                      modello: Alias tenetur.
                      prezzo: 0.78429174
                      quantita: 7708216444412231043
                      taglia: Nobis minima sit a qui.
            store:
                type: string
                description: Codice Store
                example: Consequatur sit vero illum qui.
            tipologiaOrdine:
                type: string
                description: Tipologia Ordine
                example: corriere
                enum:
                    - corriere
                    - negozio
        example:
            cognomeCliente: Omnis nemo eos ad esse.
            dataOrdine: Mollitia eveniet consequatur.
            idOrdine: Eos quia ut ipsum similique.
            nomeCliente: Sit eos quia et consequatur magnam itaque.
            righeOrdine:
                - barcode: Et consectetur.
                  colore: Voluptatem non sunt ea.
                  modello: Alias tenetur.
                  prezzo: 0.78429174
                  quantita: 7708216444412231043
                  taglia: Nobis minima sit a qui.
                - barcode: Et consectetur.
                  colore: Voluptatem non sunt ea.
                  modello: Alias tenetur.
                  prezzo: 0.78429174
                  quantita: 7708216444412231043
                  taglia: Nobis minima sit a qui.
                - barcode: Et consectetur.
                  colore: Voluptatem non sunt ea.
                  modello: Alias tenetur.
                  prezzo: 0.78429174
                  quantita: 7708216444412231043
                  taglia: Nobis minima sit a qui.
                - barcode: Et consectetur.
                  colore: Voluptatem non sunt ea.
                  modello: Alias tenetur.
                  prezzo: 0.78429174
                  quantita: 7708216444412231043
                  taglia: Nobis minima sit a qui.
            store: Fugit quia maxime sed.
            tipologiaOrdine: negozio
        required:
            - idOrdine
            - store
            - tipologiaOrdine
    MsordermsCreateOrderResponseBody:
        title: 'Mediatype identifier: statoordine; view=default'
        type: object
        properties:
            ordineId:
                type: string
                description: Id Ordine
                example: Molestias sunt necessitatibus odit atque.
            statoOrdine:
                type: string
                example: in elaborazione
                enum:
                    - da elaborare
                    - in elaborazione
                    - presa in carico
                    - confermato
                    - annullato
        description: CreateOrderResponseBody result type (default view)
        example:
            ordineId: In molestiae optio esse mollitia.
            statoOrdine: confermato
    MsordermsGetStatusOrderByIDNoMatchResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: getStatusOrderById_no_match_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    MsordermsGetStatusOrderByIDResponseBody:
        title: 'Mediatype identifier: statoordine; view=default'
        type: object
        properties:
            ordineId:
                type: string
                description: Id Ordine
                example: Est nostrum autem aliquid.
            statoOrdine:
                type: string
                example: confermato
                enum:
                    - da elaborare
                    - in elaborazione
                    - presa in carico
                    - confermato
                    - annullato
        description: GetStatusOrderByIdResponseBody result type (default view)
        example:
            ordineId: Repellendus cumque optio quo modi magnam.
            statoOrdine: in elaborazione
    RigaOrdineRequestBody:
        title: RigaOrdineRequestBody
        type: object
        properties:
            barcode:
                type: string
                description: Barcode Articolo
                example: Quidem quia alias expedita ipsum debitis.
            colore:
                type: string
                description: Codice Colore
                example: Adipisci labore.
            modello:
                type: string
                description: Codice Articolo
                example: Unde qui vitae quod temporibus voluptatem.
            prezzo:
                type: number
                description: Prezzo
                example: 0.338012
                format: float
            quantita:
                type: integer
                description: Numero pezzi
                example: 948708886759015634
                format: int64
            taglia:
                type: string
                description: Codice Taglia
                example: Atque corrupti iure.
        example:
            barcode: Fuga aspernatur est quia et magnam qui.
            colore: Corrupti laborum voluptatem culpa quibusdam.
            modello: Incidunt dolores deleniti voluptatem veniam.
            prezzo: 0.1066541
            quantita: 7750939666605741140
            taglia: Quas in voluptas.
        required:
            - barcode
            - quantita
